//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LegacyDaedalus.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LegacyDaedalusParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ILegacyDaedalusVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.daedalusFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDaedalusFile([NotNull] LegacyDaedalusParser.DaedalusFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.blockDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockDef([NotNull] LegacyDaedalusParser.BlockDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.inlineDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineDef([NotNull] LegacyDaedalusParser.InlineDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.externFunctionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternFunctionDecl([NotNull] LegacyDaedalusParser.ExternFunctionDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDef([NotNull] LegacyDaedalusParser.FunctionDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.constDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstDef([NotNull] LegacyDaedalusParser.ConstDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.classDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDef([NotNull] LegacyDaedalusParser.ClassDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.prototypeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrototypeDef([NotNull] LegacyDaedalusParser.PrototypeDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.instanceDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceDef([NotNull] LegacyDaedalusParser.InstanceDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.instanceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceDecl([NotNull] LegacyDaedalusParser.InstanceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] LegacyDaedalusParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.constArrayDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstArrayDef([NotNull] LegacyDaedalusParser.ConstArrayDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.constArrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstArrayAssignment([NotNull] LegacyDaedalusParser.ConstArrayAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.constValueDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstValueDef([NotNull] LegacyDaedalusParser.ConstValueDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.constValueAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstValueAssignment([NotNull] LegacyDaedalusParser.ConstValueAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.varArrayDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarArrayDecl([NotNull] LegacyDaedalusParser.VarArrayDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.varArrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarArrayAssignment([NotNull] LegacyDaedalusParser.VarArrayAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.varValueDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarValueDecl([NotNull] LegacyDaedalusParser.VarValueDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.varValueAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarValueAssignment([NotNull] LegacyDaedalusParser.VarValueAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] LegacyDaedalusParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.parameterDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDecl([NotNull] LegacyDaedalusParser.ParameterDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementBlock([NotNull] LegacyDaedalusParser.StatementBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LegacyDaedalusParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] LegacyDaedalusParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] LegacyDaedalusParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.elseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseBlock([NotNull] LegacyDaedalusParser.ElseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.elseIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfBlock([NotNull] LegacyDaedalusParser.ElseIfBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlock([NotNull] LegacyDaedalusParser.IfBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.ifBlockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlockStatement([NotNull] LegacyDaedalusParser.IfBlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] LegacyDaedalusParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] LegacyDaedalusParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] LegacyDaedalusParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] LegacyDaedalusParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bitMoveExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitMoveExpression([NotNull] LegacyDaedalusParser.BitMoveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>valueExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpression([NotNull] LegacyDaedalusParser.ValueExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>eqExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqExpression([NotNull] LegacyDaedalusParser.EqExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>addExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpression([NotNull] LegacyDaedalusParser.AddExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompExpression([NotNull] LegacyDaedalusParser.CompExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logOrExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogOrExpression([NotNull] LegacyDaedalusParser.LogOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binAndExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinAndExpression([NotNull] LegacyDaedalusParser.BinAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binOrExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinOrExpression([NotNull] LegacyDaedalusParser.BinOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultExpression([NotNull] LegacyDaedalusParser.MultExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracketExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracketExpression([NotNull] LegacyDaedalusParser.BracketExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] LegacyDaedalusParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>logAndExpression</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogAndExpression([NotNull] LegacyDaedalusParser.LogAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.arrayIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayIndex([NotNull] LegacyDaedalusParser.ArrayIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.arraySize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySize([NotNull] LegacyDaedalusParser.ArraySizeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>integerLiteralValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteralValue([NotNull] LegacyDaedalusParser.IntegerLiteralValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>floatLiteralValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteralValue([NotNull] LegacyDaedalusParser.FloatLiteralValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringLiteralValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteralValue([NotNull] LegacyDaedalusParser.StringLiteralValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nullLiteralValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLiteralValue([NotNull] LegacyDaedalusParser.NullLiteralValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>noFuncLiteralValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoFuncLiteralValue([NotNull] LegacyDaedalusParser.NoFuncLiteralValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionCallValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallValue([NotNull] LegacyDaedalusParser.FunctionCallValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>referenceValue</c>
	/// labeled alternative in <see cref="LegacyDaedalusParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceValue([NotNull] LegacyDaedalusParser.ReferenceValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.referenceAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceAtom([NotNull] LegacyDaedalusParser.ReferenceAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReference([NotNull] LegacyDaedalusParser.ReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.dataType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataType([NotNull] LegacyDaedalusParser.DataTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.nameNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameNode([NotNull] LegacyDaedalusParser.NameNodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.parentReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentReference([NotNull] LegacyDaedalusParser.ParentReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] LegacyDaedalusParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.addOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOperator([NotNull] LegacyDaedalusParser.AddOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.bitMoveOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitMoveOperator([NotNull] LegacyDaedalusParser.BitMoveOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.compOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOperator([NotNull] LegacyDaedalusParser.CompOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.eqOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqOperator([NotNull] LegacyDaedalusParser.EqOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] LegacyDaedalusParser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.multOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultOperator([NotNull] LegacyDaedalusParser.MultOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.binAndOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinAndOperator([NotNull] LegacyDaedalusParser.BinAndOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.binOrOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinOrOperator([NotNull] LegacyDaedalusParser.BinOrOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.logAndOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogAndOperator([NotNull] LegacyDaedalusParser.LogAndOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LegacyDaedalusParser.logOrOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogOrOperator([NotNull] LegacyDaedalusParser.LogOrOperatorContext context);
}
